apiVersion: apps/v1
kind: Deployment 
metadata:
  name: orders
spec: 
  replicas: 1
  selector:
    matchLabels: 
      app: orders 
  template: 
    metadata:
      labels: 
        app: orders
    spec:
      containers: 
        - name: orders-container
          image: 451947743144.dkr.ecr.us-east-1.amazonaws.com/frontend@sha256:c65c41b4bbce344df010f59dc8ab27737bbf0193dfcaaf0b77bc6a8cdba9178d
          ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata: 
  name: orders-service              # ingress inside give this name as service name
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector: 
    app: orders